version: '3.0'
services:
  dev-db:
    image: postgres:13
    ports:
    -   5432:5432
    environment:
       POSTGRES: postgres
       POSTGRES_PASSWORD: 123
       POSTGRES_DB: nest
    networks:
      - freecodecamp
  test-db:
    image: postgres:13
    ports:
    -   5433:5432
    environment:
       POSTGRES: postgres
       POSTGRES_PASSWORD: 123
       POSTGRES_DB: nest
    networks:
      - freecodecamp
networks:
  freecodecamp: